/*
 * To chang
 @Override
 public Rectangle getBounds()
 {
 System.out.println("getBounds");
 }

 @Override
 public Rectangle2D getBounds2D()
 {
 System.out.println("getBounds2D");
 }

 @Override
 public boolean contains(double arg0, double arg1)
 {
 System.out.println("contains");
 }

 @Override
 public boolean contains(Point2D p)
 {
 System.out.println("contains");
 }

 @Override
 public boolean intersects(double arg0, double arg1, double arg2, double arg3)
 {
 System.out.println("intersects");
 }

 @Override
 public boolean intersects(Rectangle2D r)
 {
 System.out.println("intersects");
 }

 @Override
 public boolean contains(double arg0, double arg1, double arg2, double arg3)
 {
 System.out.println("contains");
 }

 @Override
 public boolean contains(Rectangle2D r)
 {
 System.out.println("contains");
 }

 @Override
 public PathIterator getPathIterator(AffineTransform at)
 {
 System.out.println("getPathIterator");
 }

 @Override
 public PathIterator getPathIterator(AffineTransform arg0, double arg1)
 {
 System.out.println("getPathIterator");
 }
 } this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import elements.CButton;
import elements.IconDownloader;
import elements.MediaElement;
import gui.Gui;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import misc.Utils;

/**
 *
 * @author aerr
 */
public class EditAlbum extends javax.swing.JDialog
{

  /**
   * A return status code - returned if Cancel button has been pressed
   */
  public static final int RET_CANCEL = 0;
  /**
   * A return status code - returned if OK button has been pressed
   */
  public static final int RET_OK = 1;
  /**
   * A return status code - returned if apply button has been pressed
   */
  public static final int RET_APPLY = 2;
  private final CButton button;

  public EditAlbum(java.awt.Frame parent, CButton button)
  {
    super(parent, true);
    initComponents();
    this.button = button;

    setLocationRelativeTo(parent);
    this.getContentPane().setBackground(new Color(39, 39, 39));

    titleTextField.setText(this.button.getText());
    customSearchTextField.setText("");
    icon.setIcon(this.button.getIcon());
    okButton.grabFocus();

    // Close the dialog when Esc is pressed
    String cancelName = "cancel";
    InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
    ActionMap actionMap = getRootPane().getActionMap();
    actionMap.put(cancelName, new AbstractAction()
          {
            public void actionPerformed(ActionEvent e)
            {
              doClose(RET_CANCEL);
            }
    });
  }

  /**
   * @return the return status of this dialog - one of RET_OK or RET_CANCEL
   */
  public int getReturnStatus()
  {
    return returnStatus;
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel2 = new javax.swing.JLabel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    titleTextField = new javax.swing.JTextField();
    searchTextField = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    replaceTextField = new javax.swing.JTextField();
    applyButton = new javax.swing.JButton();
    icon = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    customSearchTextField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    directUrlTextField = new javax.swing.JTextField();

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/Bundle"); // NOI18N
    jLabel2.setText(bundle.getString("EditAlbum.jLabel2.text")); // NOI18N

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("elements/Bundle"); // NOI18N
    setTitle(bundle1.getString("EditAlbum.title")); // NOI18N
    setAlwaysOnTop(true);
    setBackground(new java.awt.Color(39, 39, 39));
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        closeDialog(evt);
      }
    });

    okButton.setText(bundle.getString("EditAlbum.okButton.text")); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });

    cancelButton.setText(bundle.getString("EditAlbum.cancelButton.text")); // NOI18N
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText(bundle.getString("EditAlbum.jLabel1.text")); // NOI18N

    titleTextField.setBackground(new java.awt.Color(204, 204, 204));
    titleTextField.setText(bundle.getString("EditAlbum.titleTextField.text")); // NOI18N
    titleTextField.setBorder(null);
    titleTextField.addCaretListener(new javax.swing.event.CaretListener()
    {
      public void caretUpdate(javax.swing.event.CaretEvent evt)
      {
        titleTextFieldCaretUpdate(evt);
      }
    });

    searchTextField.setBackground(new java.awt.Color(204, 204, 204));
    searchTextField.setText(bundle1.getString("NewOkCancelDialog.customSearchTextField.text")); // NOI18N
    searchTextField.setBorder(null);

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText(bundle.getString("EditAlbum.jLabel3.text")); // NOI18N

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(204, 204, 204));
    jLabel4.setText(bundle.getString("EditAlbum.jLabel4.text")); // NOI18N

    replaceTextField.setBackground(new java.awt.Color(204, 204, 204));
    replaceTextField.setText(bundle1.getString("NewOkCancelDialog.customSearchTextField.text")); // NOI18N
    replaceTextField.setBorder(null);

    applyButton.setText(bundle.getString("EditAlbum.applyButton.text")); // NOI18N
    applyButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        applyButtonActionPerformed(evt);
      }
    });

    icon.setBackground(new java.awt.Color(39, 39, 39));
    icon.setForeground(new java.awt.Color(255, 255, 255));
    icon.setText(bundle.getString("EditAlbum.icon.text")); // NOI18N
    icon.setBorder(null);
    icon.setHideActionText(true);
    icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    icon.setMaximumSize(Utils.ICON_DIMENSION);
    icon.setMinimumSize(Utils.ICON_DIMENSION);
    icon.setPreferredSize(Utils.ICON_DIMENSION);
    icon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText(bundle.getString("EditAlbum.jLabel5.text")); // NOI18N

    jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(204, 204, 204));
    jLabel6.setText(bundle.getString("EditAlbum.jLabel6.text")); // NOI18N

    customSearchTextField.setBackground(new java.awt.Color(204, 204, 204));
    customSearchTextField.setText(bundle.getString("EditAlbum.customSearchTextField.text")); // NOI18N

    jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(204, 204, 204));
    jLabel7.setText(bundle.getString("EditAlbum.jLabel7.text")); // NOI18N

    directUrlTextField.setBackground(new java.awt.Color(204, 204, 204));
    directUrlTextField.setText(bundle1.getString("NewOkCancelDialog.customSearchTextField.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addGroup(layout.createSequentialGroup()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(replaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(titleTextField))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(applyButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelButton))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(directUrlTextField, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(customSearchTextField))
                .addGap(25, 25, 25))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel7)
                  .addComponent(jLabel5)
                  .addComponent(jLabel6))
                .addGap(217, 217, 217)))
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addGap(7, 7, 7)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4)
          .addComponent(replaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(customSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(directUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(46, 46, 46)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(okButton)
          .addComponent(applyButton))
        .addContainerGap())
    );

    getRootPane().setDefaultButton(okButton);
    titleTextField.getAccessibleContext().setAccessibleName(bundle.getString("EditAlbum.titleTextField.AccessibleContext.accessibleName")); // NOI18N

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Closes the dialog
   */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
      doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    doClose(RET_OK);
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    doClose(RET_CANCEL);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void applyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_applyButtonActionPerformed
  {//GEN-HEADEREND:event_applyButtonActionPerformed
    doClose(RET_APPLY);
  }//GEN-LAST:event_applyButtonActionPerformed

  private void titleTextFieldCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_titleTextFieldCaretUpdate
  {//GEN-HEADEREND:event_titleTextFieldCaretUpdate
    if (button.getText().equals(titleTextField.getText()) && customSearchTextField.getText().isEmpty())
      return;
    customSearchTextField.setText(titleTextField.getText());
  }//GEN-LAST:event_titleTextFieldCaretUpdate

  private void doClose(int retStatus)
  {
    returnStatus = retStatus;

    if (returnStatus != RET_CANCEL)
    {
      if (!button.getText().equals(titleTextField.getText()))
      {
        button.setText(titleTextField.getText());
        if (customSearchTextField.getText().isEmpty()
            && directUrlTextField.getText().isEmpty())
          new IconDownloader(button, icon).execute();
      }

      if (!directUrlTextField.getText().isEmpty())
        try
        {
          new IconDownloader(button, icon, new URL(directUrlTextField.getText())).execute();
        } catch (MalformedURLException ex)
        {
          Logger.getLogger(EditAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
      else if (!customSearchTextField.getText().isEmpty())
        new IconDownloader(button, icon, customSearchTextField.getText()).execute();

      final String search = searchTextField.getText();
      final String replace = replaceTextField.getText();
      if (!search.isEmpty())
      {
        for (MediaElement mediaElement : button.getMedias())
          mediaElement.setName(mediaElement.getName().replace(search, replace));
        Gui.getInstance().updateSearchBar();
      }
    }

    if (returnStatus != RET_APPLY)
    {
      setVisible(false);
      dispose();
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton applyButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField customSearchTextField;
  private javax.swing.JTextField directUrlTextField;
  private javax.swing.JButton icon;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField replaceTextField;
  private javax.swing.JTextField searchTextField;
  private javax.swing.JTextField titleTextField;
  // End of variables declaration//GEN-END:variables

  private int returnStatus = RET_CANCEL;
}
