package gui;

import database.DatabaseSaver;
import elements.CButton;
import elements.IconDownloader;
import elements.ListManager;
import elements.MediaElement;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.Icon;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import listing.FileWalker;
import misc.Utils;

/**
 *
 * @author aerr
 */
public class EditAlbum extends javax.swing.JDialog
{

  /**
   * A return status code - returned if Cancel button has been pressed
   */
  public static final int RET_CANCEL = 0;
  /**
   * A return status code - returned if OK button has been pressed
   */
  public static final int RET_OK = 1;
  /**
   * A return status code - returned if apply button has been pressed
   */
  public static final int RET_APPLY = 2;
  /**
   * A return status code - returned if remove button has been pressed
   */
  public static final int RET_REMOVE = 3;
  private final CButton button;

  public EditAlbum(java.awt.Frame parent, CButton button)
  {
    super(parent, true);
    this.button = button;
    initComponents();

    setLocationRelativeTo(parent);
    this.getContentPane().setBackground(new Color(89, 89, 89));

    titleTextField.setText(this.button.getText());
    titleTextField.grabFocus();
    customSearchTextField.setText("");
    icon.setIcon(this.button.getIcon());

    String cancelName = "cancel";
    InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
    ActionMap actionMap = getRootPane().getActionMap();
    actionMap.put(cancelName, new AbstractAction()
          {
            public void actionPerformed(ActionEvent e)
            {
              doClose(RET_CANCEL);
            }
    });
  }

  /**
   * @return the return status of this dialog - one of RET_OK or RET_CANCEL
   */
  public int getReturnStatus()
  {
    return returnStatus;
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    titleTextField = new javax.swing.JTextField();
    searchTextField = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    replaceTextField = new javax.swing.JTextField();
    applyButton = new javax.swing.JButton();
    icon = new JButton()
    {
      @Override
      public void setIcon(Icon defaultIcon)
      {
        super.setIcon(defaultIcon);
        if (defaultIcon != button.getIcon())
        DatabaseSaver.save();
      }
    };
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    customSearchTextField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    directUrlTextField = new javax.swing.JTextField();
    removeButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Edit Album");
    setAlwaysOnTop(true);
    setBackground(new java.awt.Color(39, 39, 39));
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        closeDialog(evt);
      }
    });

    okButton.setBackground(removeButton.getBackground());
    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });

    cancelButton.setBackground(removeButton.getBackground());
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Title:");

    titleTextField.setBackground(new java.awt.Color(204, 204, 204));
    titleTextField.setText("jTextField1");
    titleTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(4, 5, 4, 5)));
    titleTextField.addCaretListener(new javax.swing.event.CaretListener()
    {
      public void caretUpdate(javax.swing.event.CaretEvent evt)
      {
        titleTextFieldCaretUpdate(evt);
      }
    });

    searchTextField.setBackground(new java.awt.Color(204, 204, 204));
    searchTextField.setBorder(titleTextField.getBorder());

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Replace in files:");

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(216, 216, 216));
    jLabel4.setText("with");

    replaceTextField.setBackground(new java.awt.Color(204, 204, 204));
    replaceTextField.setBorder(titleTextField.getBorder());

    applyButton.setBackground(removeButton.getBackground());
    applyButton.setText("Apply");
    applyButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        applyButtonActionPerformed(evt);
      }
    });

    icon.setBackground(new java.awt.Color(89, 89, 89));
    icon.setForeground(new java.awt.Color(255, 255, 255));
    icon.setBorder(null);
    icon.setBorderPainted(false);
    icon.setContentAreaFilled(false);
    icon.setHideActionText(true);
    icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    icon.setMaximumSize(Utils.ICON_DIMENSION);
    icon.setMinimumSize(Utils.ICON_DIMENSION);
    icon.setPreferredSize(Utils.ICON_DIMENSION);
    icon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Picture:");

    jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(216, 216, 216));
    jLabel6.setText("Custom search:");

    customSearchTextField.setBackground(new java.awt.Color(204, 204, 204));
    customSearchTextField.setBorder(titleTextField.getBorder());
    customSearchTextField.setText("");

    jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(216, 216, 216));
    jLabel7.setText("Direct URL:");

    directUrlTextField.setBackground(new java.awt.Color(204, 204, 204));
    directUrlTextField.setBorder(titleTextField.getBorder());

    removeButton.setBackground((System.getProperty("os.name").equals("Linux")) ? new Color(150, 150, 150) : null);
    removeButton.setText("Remove");
    removeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        removeButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addGroup(layout.createSequentialGroup()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(replaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(titleTextField))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(removeButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(applyButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelButton))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(directUrlTextField, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(customSearchTextField))
                .addGap(25, 25, 25))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel7)
                  .addComponent(jLabel5)
                  .addComponent(jLabel6))
                .addGap(217, 217, 217)))
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addGap(7, 7, 7)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4)
          .addComponent(replaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(customSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(directUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(46, 46, 46)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(okButton)
          .addComponent(applyButton)
          .addComponent(removeButton))
        .addContainerGap())
    );

    getRootPane().setDefaultButton(okButton);
    titleTextField.getAccessibleContext().setAccessibleName("");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Closes the dialog
   */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
      doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    doClose(RET_OK);
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    doClose(RET_CANCEL);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void applyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_applyButtonActionPerformed
  {//GEN-HEADEREND:event_applyButtonActionPerformed
    doClose(RET_APPLY);
  }//GEN-LAST:event_applyButtonActionPerformed

  private void titleTextFieldCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_titleTextFieldCaretUpdate
  {//GEN-HEADEREND:event_titleTextFieldCaretUpdate
    if (button.getText().equals(titleTextField.getText()) && customSearchTextField.getText().isEmpty())
      return;
    customSearchTextField.setText(titleTextField.getText());
  }//GEN-LAST:event_titleTextFieldCaretUpdate

  private void removeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeButtonActionPerformed
  {//GEN-HEADEREND:event_removeButtonActionPerformed
    doClose(RET_REMOVE);
  }//GEN-LAST:event_removeButtonActionPerformed

  private void doClose(int retStatus)
  {
    returnStatus = retStatus;
    if (returnStatus == RET_REMOVE)
      addAndRemoveButton(true);
    else if (returnStatus != RET_CANCEL)
    {
      if (!button.getText().equals(titleTextField.getText()))
      {
        button.setText(titleTextField.getText());
        addAndRemoveButton(false);
        ListManager.searchBarUpdate();
        if (customSearchTextField.getText().isEmpty()
            && directUrlTextField.getText().isEmpty())
          new IconDownloader(button, icon).execute();
      }

      if (!directUrlTextField.getText().isEmpty())
        try
        {
          new IconDownloader(button, icon, new URL(directUrlTextField.getText())).execute();
        } catch (MalformedURLException ex)
        {
          Logger.getLogger(EditAlbum.class.getName()).log(Level.SEVERE, null, ex);
        }
      else if (!customSearchTextField.getText().isEmpty())
        new IconDownloader(button, icon, customSearchTextField.getText()).execute();

      final String search = searchTextField.getText();
      final String replace = replaceTextField.getText();
      if (!search.isEmpty())
      {
        for (MediaElement mediaElement : button.getMedias())
          mediaElement.setName(mediaElement.getName().replace(search, replace));
        ListManager.searchBarUpdate();
      }
    }

    if (returnStatus != RET_APPLY)
    {
      if (returnStatus != RET_CANCEL)
      {
        ListManager.reloadList(true);
        DatabaseSaver.save();
      }
      setVisible(false);
      dispose();
    }
  }

  private void addAndRemoveButton(boolean justRemove)
  {
    boolean added = false;
    for (Iterator<CButton> it = FileWalker.getInstance().getSetButtons().iterator(); it.hasNext();)
    {
      CButton cButton = it.next();
      if (cButton == button)
      {
        it.remove();
        if (justRemove)
          return;
      }
      // Merge with other album with the same name
      else if (!added && button.getText().equals(cButton.getText()))
      {
        added = true;
        for (MediaElement mediaElement : button.getMedias())
          cButton.getMedias().add(mediaElement);
      }
    }
    // If not merge, simply add
    if (!added)
      FileWalker.getInstance().getSetButtons().add(button);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton applyButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField customSearchTextField;
  private javax.swing.JTextField directUrlTextField;
  private javax.swing.JButton icon;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JButton okButton;
  private javax.swing.JButton removeButton;
  private javax.swing.JTextField replaceTextField;
  private javax.swing.JTextField searchTextField;
  private javax.swing.JTextField titleTextField;
  // End of variables declaration//GEN-END:variables

  private int returnStatus = RET_CANCEL;
}
